@startuml color-clock-top-level
'_______________________________________________________________________
' Legend
'_______________________________________________________________________
' <|-- Inheritance, e.g. ParentClass --|> ChildClass
' <|.. Realization
' <... Dependency
' <--- Directed Association, classA knows of classB, but not vice versa
' *--- Composition
' o--- Aggregation
' ---- Association, need to communicate, no strong relationship
'_______________________________________________________________________

'_______________________________________________________________________
' Style
'_______________________________________________________________________
!include style.puml
!include notes.puml

class TopLevel       <<top-level>>
class ParticipantCtrl<<major>>
class TimeController <<major>>
class ColorClock     <<major>>

skinparam MinClassWidth         120
hide members

'_______________________________________________________________________


'json "Class Description" as class_desc {
'  "TopLevel           " : ""
', "ColorClock         " : "Light display mapping time to color."
', "TimeDisplay        " : ""
', "TimeController     " : ""
', "ParticipantCtrl    " : "Logic for user interface control."
', "MomentarySwitch    " : "State logic for buttons."
', "FluxClock          " : "Wrapper class for real-time clock module."
'}

'note "Used for time set and\nparticipant control" as Note0
MomentarySwitch ..  btn_note
FluxClock       ..  flux_clock_note
TimeDisplay     ..  time_disp_note

note "States for:\n- IDLE\n- TIME_SET" as Note3
TopLevelState   ..     Note3

TopLevel        *-down- TimeController
TopLevel        *-down- ParticipantCtrl

TopLevel        o---     "4" ColorClock
TopLevel        *-down--- "11" MomentarySwitch
TopLevel        o-down--- FluxClock
TopLevel        o-down--- TimeDisplay
TopLevel        *-down--- TopLevelState

!include legend.puml

@enduml
