@startuml class-user-ctrl
'_______________________________________________________________________
' Legend
'_______________________________________________________________________
' <|-- Inheritance, e.g. ParentClass --|> ChildClass
' <|.. Realization
' <... Dependency
' <--- Directed Association, classA knows of classB, but not vice versa
' *--- Composition
' o--- Aggregation
' ---- Association, need to communicate, no strong relationship
'_______________________________________________________________________

!include legend.puml
!include notes.puml
hide btn_note
hide time_disp_note
hide instantiate_note

'_______________________________________________________________________
' Style
'_______________________________________________________________________
!include style.puml
hide members

class ParticipantCtrl<<major>>
class DS3231         <<api>>

'_______________________________________________________________________
ParticipantCtrl *-down-   "8" Button
ParticipantCtrl o-down-   ColorClock

ColorClock      o-down-   FluxClock
ColorClock      *-down-   "*" RgbColor
ColorClock       .down.>  TimeCalcs

FluxClock       *-down-   DS3231
DS3231          ..        flux_clock_note

Button *-down-   SwitchState

RgbColor        --        HsvColor

@enduml
