@startuml

!include style.puml

hide empty description

skinparam Linetype              spline

state "Button Press State Diagram"  as GetButtonPressType

state GetButtonPressType {

  state "IDLE" as BTN_IDLE

  BTN_IDLE        --> PRESS    : button\lpressed
  PRESS       --> HOLD
  HOLD        --> RET_NONE
  RET_NONE : Hold too short\nto register\npress

  HOLD        --> RELEASE
  RELEASE     --> RET_LONG : long \npress
  RELEASE     --> WAIT     : short\npress
  WAIT        --> PRESS    : new\lpress\n\ninc\nbtn\npress\ncount

  WAIT        --> RET_SINGLE_PRESS
  WAIT        --> RET_DOUBLE_PRESS
  WAIT        --> RET_TRIPLE_PRESS

  WAIT: Wait for another\npress to determine \nmulti-press input
  'RET_SINGLE_PRESS -->  [*]
  'RET_DOUBLE_PRESS -->  [*]
  'RET_TRIPLE_PRESS -->  [*]
  'RET_NONE         -->  [*]
  'RET_LONG    --> [*]
}

@enduml
