@startuml color-clock-top-level

!include style.puml

'_______________________________________________________________________
' Style Overrides
'_______________________________________________________________________

class TopLevel       <<top-level>>
class ParticipantCtrl<<major>>
class TimeController <<major>>
class ColorClock     <<major>>

'_______________________________________________________________________
' Legend
'_______________________________________________________________________
' --|> Inheritance, child on top  e.g. ChildClass  --|> ParentClass
' <|-- Inheritance, parent on top e.g. ParentClass --|> ChildClass
' --   Association, need to communicate, no strong relationship
' -->  Directed Association, classA knows of classB, but not vice versa
' *--  Composition
' o--  Aggregation
' ..>  Dependency
' <|.. Realization
'_______________________________________________________________________

skinparam MinClassWidth         120
hide members


'json "Class Description" as class_desc {
'  "TopLevel           " : ""
', "ColorClock         " : "Light display mapping time to color."
', "TimeDisplay        " : ""
', "TimeController     " : ""
', "ParticipantCtrl    " : "Logic for user interface control."
', "MomentarySwitch    " : "State logic for buttons."
', "FluxClock          " : "Wrapper class for real-time clock module."
'}

note "Used for time set and\nparticipant control" as Note0
MomentarySwitch ..     Note0

note "Wrapper for real-time\nclock module" as Note1
FluxClock       ..     Note1

note "Wrapper for alphanumeric\ntime set display" as Note2
TimeDisplay     ..     Note2

note "States for:\n- IDLE\n- TIME_SET\n- USER_CTRL" as Note3
TopLevelState   ..     Note3

TopLevel        *-down- TimeController
TopLevel        *-down- ParticipantCtrl

TopLevel        o---     "*" ColorClock
TopLevel        *-down--- "11" MomentarySwitch
TopLevel        o-down--- FluxClock
TopLevel        o-down--- TimeDisplay
TopLevel        *-down--- TopLevelState

!include legend.puml

@enduml
