@startuml color-clock-top-level

!include style-lite-colors.puml
!include style.puml

'_______________________________________________________________________
' Style Overrides
'_______________________________________________________________________

class ParticipantCtrl<<major>>
class TimeController <<major>>

'_______________________________________________________________________
' Legend
'_______________________________________________________________________
' --|> Inheritance, child on top  e.g. ChildClass  --|> ParentClass
' <|-- Inheritance, parent on top e.g. ParentClass --|> ChildClass
' --   Association, need to communicate, no strong relationship
' -->  Directed Association, classA knows of classB, but not vice versa
' *--  Composition
' o--  Aggregation
' ..>  Dependency
' <|.. Realization
'_______________________________________________________________________

skinparam MinClassWidth         120
hide members


json "Class Description" as class_desc {
  "TopLevel           " : ""
, "ColorClock         " : "Light display mapping time to color."
, "TimeDisplay        " : ""
, "TimeController     " : ""
, "ParticipantCtrl    " : "Logic for user interface control."
, "MomentarySwitch    " : "State logic for buttons."
, "FluxClock          " : "Wrapper class for real-time clock module."
}

note "Used for time set and\nparticipant control" as Note0

MomentarySwitch ..     Note0

TopLevel        o-down- FluxClock
TopLevel        o-down- TimeDisplay

TopLevel        *-down- TimeController
TopLevel        *-down- MomentarySwitch
TopLevel        *-down- TopLevelState
TopLevel        *-down- ParticipantCtrl

TopLevel        -- ColorClock




@enduml
