@startuml nine-eighty-alarm-base-uml
'_______________________________________________________________________
' Legend
'_______________________________________________________________________
' --|> Inheritance, child on top  e.g. ChildClass  --|> ParentClass
' <|-- Inheritance, parent on top e.g. ParentClass --|> ChildClass
' --   Association, need to communicate, no strong relationship
' -->  Directed Association, classA knows of classB, but not vice versa
' *--  Composition
' o--  Aggregation
' ..>  Dependency
' <|.. Realization
'_______________________________________________________________________


'_______________________________________________________________________
' Style
'_______________________________________________________________________

!include style.puml
!include legend.puml

class ParticipantCtrl<<major>>
class DS3231         <<api>>

'_______________________________________________________________________
ParticipantCtrl *-down-   "8" MomentarySwitch
ParticipantCtrl o-down-   ColorClock

ColorClock      o-down-   FluxClock
ColorClock      *-down-   "*" RgbColor
ColorClock       .down.>  TimeCalcs

note "Real-time clock API" as Note1
FluxClock       *-down-   DS3231
DS3231          ..        Note1

MomentarySwitch *-down-   SwitchState

RgbColor        --        HsvColor

@enduml
